name: Development

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  dev:
    runs-on: ubuntu-latest # Correct runner
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Clear space to remove unused folders
        run: |
          rm -rf /usr/share/dotnet
          rm -rf /opt/ghc
          rm -rf "/usr/local/share/boost"
          rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image name and tag
        id: image_meta
        run: |
          IMAGE_NAME="docker.io/${{ vars.DOCKERHUB_REPO }}/${{ vars.DOCKERHUB_IMG }}"
          IMAGE_TAG="slim-latest" # Choose your desired tag here (e.g., slim-latest, base-v1)
          echo "IMAGE_NAME_TAGGED=${IMAGE_NAME}:${IMAGE_TAG}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.image_meta.outputs.IMAGE_NAME_TAGGED }}
